function add_gate(gate)
  gate:addtoworld()
  gate:childbyoid(328):addtoworld()
  gate:lowergate(10000, 0.5)
  pause(0.1)
  gate:activateshockwave()
end

function on_label(label)
  if label == "doit" then
    pause(2)
    add_gate(gomgr.getbyoid(324))
    add_gate(gomgr.getbyoid(345))
    add_gate(gomgr.getbyoid(346))
    add_gate(gomgr.getbyoid(347))
    add_gate(gomgr.getbyoid(348))
    add_gate(gomgr.getbyoid(349))
    add_gate(gomgr.getbyoid(350))
    add_gate(gomgr.getbyoid(351))
    add_gate(gomgr.getbyoid(352))
    add_gate(gomgr.getbyoid(353))
    add_gate(gomgr.getbyoid(354))
    add_gate(gomgr.getbyoid(355))
    add_gate(gomgr.getbyoid(356))
    add_gate(gomgr.getbyoid(357))
    add_gate(gomgr.getbyoid(358))
    add_gate(gomgr.getbyoid(359))
    add_gate(gomgr.getbyoid(360))
    add_gate(gomgr.getbyoid(361))
    add_gate(gomgr.getbyoid(362))
    add_gate(gomgr.getbyoid(363))
    add_gate(gomgr.getbyoid(364))
    add_gate(gomgr.getbyoid(365))
    add_gate(gomgr.getbyoid(366))
    add_gate(gomgr.getbyoid(367))
    add_gate(gomgr.getbyoid(368))
    add_gate(gomgr.getbyoid(369))
    add_gate(gomgr.getbyoid(370))
    add_gate(gomgr.getbyoid(371))
    add_gate(gomgr.getbyoid(372))
    add_gate(gomgr.getbyoid(373))
    add_gate(gomgr.getbyoid(374))
    add_gate(gomgr.getbyoid(375))
    add_gate(gomgr.getbyoid(376))
  end       
end